<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.11" />
    <PackageReference Include="YamlDotNet" Version="18.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CodeRail.Evidence\CodeRail.Evidence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Configuration\Profiles\dotnet-default.yml" />
  </ItemGroup>

</Project>
